name: CI

# Controls when the action will run. 
on:
  pull_request:
    types: [synchronize, opened]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Get date
        id: date_begin
        run: |
          echo "::set-output name=branch_name::$(date '+%Y-%m-%dT%H:%M:%SZ')"
      
      - name: Notify MyCheck (in progress)
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: MyCheck
          status: in_progress
          action_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          output: |
            {"summary":"Test Output (in progress)"}

      - name: Sleep
        run: |
          sleep 10
          
      - name: Notify MyCheck (completed)
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: MyCheck
          status: completed
          conclusion: success
          action_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          details_url: 'https://github.com/shimat'
          annotations: |
            [
              {"path":"foo.txt", "start_line":1, "end_line":2, "annotation_level":"notice", "message":"message", "title":"title"}
            ]
          output: |
            {
              "title": "title",
              "summary":"Test Output (completed)\nhttps://github.com/shimat",
              "text": "text",
              "annotations": [                
                {"path":"foo.txt", "start_line":1, "end_line":2, "annotation_level":"notice", "message":"message", "title":"title"}
              ]
            }
          
      - name: Notify another check
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ErrorCheck
          status: completed
          conclusion: failure
          action_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          details_url: 'https://github.com/shimat'
          actions: |
            [
              {"label":"label", "description":"description", "identifier":"identifier"}
            ]
          output: |
            {"summary":"Test Output (failed)"}
