name: Manual

on:
  workflow_dispatch:
    inputs:      
      foo:
        description: 'Foo'
        required: false
        default: ""

jobs:
  A:
    # name: ${{ github.event.inputs.foo }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A"

  B:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.foo == 'B' }}
    steps:
      - run: |
          echo "B"

  C:
    runs-on: ubuntu-latest
    needs: [A, B]
    if: ! failure()
    steps:
      - run: |
          echo "C"

  D:
    runs-on: ubuntu-latest
    needs: [C]
    steps:
      - run: |
          echo "D"
