name: Manual ${{ github.event.inputs.foo }}

on:
  workflow_dispatch:
    input:      
      foo:
        description: 'Foo'
        required: true

jobs:
  build:
    name: ${{ github.event.inputs.foo }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ github.event.inputs.foo }}
