name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Create dummy artifact
        run: echo Hello, world! > hoge.txt

      - uses: actions/upload-artifact@v2
        with:
          name: hoge
          path: hoge.txt
          
  release:
    if: github.event_name != 'pull_request'
    needs: build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hoge
    
      - name: Set tag name by date string
        run: echo "::set-output name=TAG_NAME::$(TZ=-9 date +'%Y-%m-%d-%H%M%S')"
        id: date

      - uses: ncipollo/release-action@40bb172bd05f266cf9ba4ff965cb61e9ee5f6d01 # v1.9.0
        with:
          artifacts: "hoge.txt"
          body: |
            - hoge
            - fuga
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.TAG_NAME }}
