name: Reusable Workflow

on:
  workflow_call:
    inputs:
      hoge:
        required: true
        type: string

jobs:  
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.hoge }}
